<?php namespace TPS\Birzha\Components;

use Cms\Classes\ComponentBase;
use Cms\Classes\Page;

class Categories extends ComponentBase
{
    public function componentDetails()
    {
        return [
            'name'        => 'Categories',
            'description' => 'List of categories'
        ];
    }

    public function defineProperties()
    {
        return [
            'featured' => [
                'title'       => 'Active categories',
                'description' => 'Filter active categories',
                'type'        => 'checkbox'
            ],
            'categoryPage' => [
                'title'       => 'Category page',
                'description' => 'Chose category page',
                'type'        => 'dropdown',
                'group'       => 'rainlab.blog::lang.settings.group_links',
            ],
            'catsPerPage' => [
                'title'             => 'Categories per page',
                'type'              => 'string',
                'validationPattern' => '^[0-9]+$',
                'validationMessage' => 'please enter numeric value',
                'default'           => '10',
            ],
        ];
    }

    public function getCategoryPageOptions()
    {
        return Page::sortBy('baseFileName')->lists('baseFileName', 'baseFileName');
    }

    public function onRun()
    {
        parent::onRun(); // TODO: Change the autogenerated stub

    }
}
