en:
  site.name: Turkmenistan state birzha
  site.short_name: ГТСБТ
  auth.login: Enter email or phone number
  auth.name: Name
  auth.surname: Surname
  auth.email: Email address
  auth.phone: Phone number
  auth.password: Password
  auth.reg_continue: Register
  auth.account_recov: Если вы забыли свой логин или пароль, просим вас
                            восстановить его по <a href="#" class="form_link">ссылке.</a>
  auth.login_to_account: Sign in
  auth.personal_data: Profile
  auth.my_announces: My announcements
  auth.no_my_announces: You have no active <br> ads at the moment.
  auth.messages: Messages
  auth.logout: Logout
  auth.add_announce: Add announcement
  auth.notifications: Notifications
  auth.no_notifications: There are no notifications
  account.company: Company
  account.legalization_number: Legalization number
  account.save: Save
  account.password_confirmation: Confirm password
  account.new_password: New password
  account.info: Account info
  account.balance: Balance
  account.balance_warning: Перед отправкой убедитесь что перевод был осуществлен верно и у вас имеется чек
  account.fill_up_balance: Fill up balance
  account.bank_details: Банковские реквизиты
  account.bank_address: Bank address
  account.bank_1: 744000, Туркменистан г.Ашгабат, Арчабиль шаелы 52
  account.bank_tax_code: Salgyt kody
  account.bank_manat_account: Manat hasaby
  account.bank_correspondent_account: Korrespondent hasaby
  account.bank_bab: BAB
  account.our_bank_details: Our реквизиты
  account.amount: Сумма
  account.upload_file: Загрузить файл
  account.nothing_chosen: Ничего не выбранo
  account.send: Отправить
  account.bank_transfer: Bank transfer
  account.online_payment: Online payment
  account.pay: Pay
  account.bank_transfer_message: Администратор просмотрит ваш документ оплаты, и средства перейдут на ваш баланс. Спасибо
  account.payment_type: Метод оплаты
  account.choose_chat: Выберите один из активных диалоговых окон чтоб начать переписку!
  account.on_site: На сайте
  account_delete: Удалить
  account.prolong: Продлить
  account.edit: Edit
  account.complete: Complete
  account.admin_checking: Admin is checking
  account.add_post: Добавить объявление (Step :step_number)
  account.lot_title: Наименование лота
  account.lot_title_example: Гидравлическое масло
  account.mark_example: ЛУКОЙЛ 46
  account.category: Категория
  account.step: Step :step_number
  account.required_fields: Пункты отмеченные  ( <span>*</span> ) обязательны для заполнения
  account.activation_required: Activation is required
  account.thanks_for_posting: Спасибо за оставленный вами запрос
  account.admin_check_and_approve: После проверки нашим Админом ваш лот будет размещен на нашем сайте!
  account.quantity_example: 3 литра
  account.currency: Валюта
  account.delivery_point_example: Mary
  account.upload_photo: Загрузить фото
  account.fee_for_publishing: За публикацию с вашего баланса будет снято :fee TMT
  account.publish: Опубликовать
  topnav.reg: Sign up
  topnav.login: Sign in
  nav.home: Home
  nav.city: Ashgabat
  page.more: More
  page.not_found: Page not found
  page.not_found_message: We're sorry, but the page you requested cannot be found.
  page.search: Search
  page.search_result: 'The search results found: :number articles'
  page.new_prods: New products
  page.prods: Products
  page.similar_prods: Из этой же категории
  page.prod_id: Lot
  page.prod_img: Image
  page.prod_title: Product
  page.prod_no: lot number
  page.prod_mark: Product mark
  page.prod_vendor: Manufacturer
  page.prod_vendor_country: Manufactured country
  page.market_type: Market type
  page.market_type_option_in: Внутренний
  page.market_type_option_out: Внешний
  page.contact_us: Обратная связь
  page.your_firstname: Ваше имя
  page.your_lastname: Ваша фамилия
  page.example: Пример
  page.example_firstname: Аман
  page.example_lastname: Аманов
  page.message: Сообщение
  page.describe_your_problem: Опишите вашу проблемму
  page.message_sent: Сообщение отправлено
  page.message_to_seller: Сообщение продавцу
  page.fio: ФИО
  page.prod_desc: Description
  page.prod_amount: Quantity
  page.prod_amount_2: Product quantity
  page.prod_price: Стартовая цена
  page.prod_price_2: Стартовая цена за единицу
  page.prod_finishdate: Дата окончания
  page.prod_kg: кг
  page.pages: Страниц
  page.prod_startdate: Дата начала
  page.measure: Единица измерения
  page.payment_cond: Условия оплаты
  page.delivery_cond: Условия поставки
  page.delivery_point: Пункт
  page.packaging: Упаковка
  page.packaging_yes: Yes
  page.packaging_no: No
  page.seller_cont: Контакты продавца
  page.buy_now: Купить сейчас
  page.send_prod_request: Отправить запрос на лот
  page.date_decrease: По убыванию
  page.date_increase: По возрастанию
  page.no_results_found: No results found
  page.sort_by_date: По дате
  footer.contacts: Контакты
  footer.tel: Тел
  footer.email: Эл. почта
  footer.address: Адрес
  footer.copyright: © TDHСMB all rights reserved
  footer.categories: Categories
  status_approved: Approved
  status_draft: Draft
  status_new: Processing
  status_denied: Denied
  status_expired: Date expired
ru:
  site.name: '«Туркменистан: золотой век»'
  site.short_name: ГТСБТ
  auth.name: Ваша имя
  auth.surname: Фамилия
  auth.login: Введите почту или номер телефона
  auth.email: Ваш электронный адрес
  auth.phone: Номер телефона
  auth.password: Пароль
  auth.reg_continue: Продолжить регистрацию
  auth.account_recov: Если вы забыли свой логин или пароль, просим вас
                            восстановить его по <a href="#" class="form_link">ссылке.</a>
  auth.login_to_account: Войти в свой профиль
  auth.personal_data: Персональные данные
  auth.my_announces: Мои объявления
  auth.no_my_announces: На данный момент <br> у вас нет активных объявлений.
  auth.messages: Сообщения
  auth.logout: Выйти
  auth.add_announce: Добавить объявление
  auth.notifications: Уведомления
  auth.no_notifications: Нет уведомлений
  account.company: Компания
  account.legalization_number: Номер легализации
  account.save: Ýatla
  account.password_confirmation: Täze açar sözüňizi tassyklaň
  account.new_password: Täze açar söz
  account.info: Персональные данные
  account.balance: Balance
  account.balance_warning: Перед отправкой убедитесь что перевод был осуществлен верно и у вас имеется чек
  account.fill_up_balance: Fill up balance
  account.bank_details: Банковские реквизиты
  account.bank_address: Bank address
  account.bank_1: 744000, Туркменистан г.Ашгабат, Арчабиль шаелы 52
  account.bank_tax_code: Налоговый код
  account.bank_manat_account: Манатный счёт
  account.bank_correspondent_account: Корреспондент счет
  account.bank_bab: МФО
  account.our_bank_details: Our реквизиты
  account.amount: Сумма
  account.upload_file: Загрузить файл
  account.nothing_chosen: Ничего не выбранo
  account.send: Отправить
  account.bank_transfer: Bank transfer
  account.online_payment: Online payment
  account.pay: Pay
  account.bank_transfer_message: Администратор просмотрит ваш документ оплаты, и средства перейдут на ваш баланс. Спасибо
  account.payment_type: Метод оплаты
  account.choose_chat: Выберите один из активных диалоговых окон чтоб начать переписку!
  account.on_site: На сайте
  account_delete: Удалить
  account.prolong: Продлить
  account.edit: Edit
  account.complete: Complete
  account.admin_checking: Admin is checking
  account.add_post: Добавить объявление (Step :step_number)
  account.lot_title: Наименование лота
  account.lot_title_example: Гидравлическое масло
  account.mark_example: ЛУКОЙЛ 46
  account.category: Категория
  account.step: Step :step_number
  account.required_fields: Пункты отмеченные  ( <span>*</span> ) обязательны для заполнения
  account.activation_required: Activation is required
  account.thanks_for_posting: Спасибо за оставленный вами запрос
  account.admin_check_and_approve: После проверки нашим Админом ваш лот будет размещен на нашем сайте!
  account.quantity_example: 3 литра
  account.currency: Валюта
  account.delivery_point_example: Mary
  account.upload_photo: Загрузить фото
  account.fee_for_publishing: За публикацию с вашего баланса будет снято :fee TMT
  account.publish: Опубликовать
  topnav.reg: Регистрация
  topnav.login: Sign in
  nav.home: Главная
  nav.city: Ашхабад
  page.more: Ещё
  page.not_found: Страница не найдена
  page.not_found_message: Сожалеем, но запрошенная вами страница не может быть найдена.
  page.search: Поиск
  page.search_result: 'По результату поиска было найдено: :number статьи'
  page.new_prods: Новые товары
  page.prods: Tовары
  page.similar_prods: Из этой же категории
  page.prod_id: Лот
  page.prod_img: Изображение
  page.prod_title: Товар
  page.prod_no: Номер лота
  page.prod_mark: Марка товара
  page.prod_vendor: Производитель
  page.prod_vendor_country: Страна производителя
  page.market_type: Market type
  page.market_type_option_in: Внутренний
  page.market_type_option_out: Внешний
  page.contact_us: Обратная связь
  page.your_firstname: Ваше имя
  page.your_lastname: Ваша фамилия
  page.example: Пример
  page.example_firstname: Аман
  page.example_lastname: Аманов
  page.message: Сообщение
  page.describe_your_problem: Опишите вашу проблемму
  page.message_sent: Сообщение отправлено
  page.message_to_seller: Сообщение продавцу
  page.fio: ФИО
  page.prod_desc: Описание
  page.prod_amount: Количество
  page.prod_amount_2: Количество товара
  page.prod_price: Стартовая цена
  page.prod_price_2: Стартовая цена за единицу
  page.prod_finishdate: Дата окончания
  page.prod_startdate: Дата начала
  page.measure: Единица измерения
  page.payment_cond: Условия оплаты
  page.delivery_cond: Условия поставки
  page.delivery_point: Пункт
  page.packaging: Упаковка
  page.packaging_yes: Есть
  page.packaging_no: Нет
  page.seller_cont: Контакты продавца
  page.buy_now: Купить сейчас
  page.send_prod_request: Отправить запрос на лот
  page.prod_kg: кг
  page.pages: Страниц
  page.date_decrease: По убыванию
  page.date_increase: По возрастанию
  page.no_results_found: No results found
  page.sort_by_date: По дате
  footer.contacts: Контакты
  footer.tel: Тел
  footer.email: Эл. почта
  footer.address: Адрес
  footer.copyright: © TDHСMB все права зашишены
  footer.categories: Categories
  status_approved: Одобрено
  status_draft: Черновик
  status_new: В обработке
  status_denied: Отменено
  status_expired: Срок истек
tm:
  site.name: Türkmenistanyň Döwlet çig-mal biržasy
  site.short_name: TDÇMB
  auth.name: Adyňyz
  auth.surname: Familiýaňyz
  auth.login: El. bukjaňyz ýa-da telefon nomeriňiz
  auth.email: El. bukjaňyz
  auth.phone: Telefon belgiňiz
  auth.password: Açar söz
  auth.reg_continue: Dowam et
  auth.account_recov: Если вы забыли свой логин или пароль, просим вас
                            восстановить его по <a href="#" class="form_link">ссылке.</a>
  auth.login_to_account: Profiliňe gir
  auth.personal_data: Hususy maglumatlar
  auth.my_announces: Meniň bildirişlerim
  auth.no_my_announces: Häzirki wagtda <br> işjeň mahabatyňyz ýok.
  auth.messages: Hatlar
  auth.logout: Çykyş
  auth.add_announce: Bildiriş goş
  auth.notifications: Habarnamalar
  auth.no_notifications: Habarnamalar ýok
  account.company: Şereket
  account.legalization_number: Legalizasiýa nomeri
  account.save: Ýatla
  account.password_confirmation: Täze açar sözüňizi tassyklaň
  account.new_password: Täze açar söz
  account.info: Şahsy maglumatlar
  account.balance: Balance
  account.balance_warning: Перед отправкой убедитесь что перевод был осуществлен верно и у вас имеется чек
  account.fill_up_balance: Fill up balance
  account.bank_details: Банковские реквизиты
  account.bank_address: Bank address
  account.bank_1: 744000, Туркменистан г.Ашгабат, Арчабиль шаелы 52
  account.bank_tax_code: Salgyt kody
  account.bank_manat_account: Manat hasaby
  account.bank_correspondent_account: Korrespondent hasaby
  account.bank_bab: BAB
  account.our_bank_details: Our реквизиты
  account.amount: Сумма
  account.upload_file: Загрузить файл
  account.nothing_chosen: Ничего не выбранo
  account.send: Отправить
  account.bank_transfer: Bank transfer
  account.online_payment: Online payment
  account.pay: Pay
  account.bank_transfer_message: Администратор просмотрит ваш документ оплаты, и средства перейдут на ваш баланс. Спасибо
  account.payment_type: Метод оплаты
  account.choose_chat: Выберите один из активных диалоговых окон чтоб начать переписку!
  account.on_site: На сайте
  account_delete: Удалить
  account.prolong: Продлить
  account.edit: Edit
  account.complete: Complete
  account.admin_checking: Admin is checking
  account.add_post: Добавить объявление (Step :step_number)
  account.lot_title: Наименование лота
  account.lot_title_example: Гидравлическое масло
  account.mark_example: ЛУКОЙЛ 46
  account.category: Категория
  account.step: Step :step_number
  account.required_fields: Пункты отмеченные  ( <span>*</span> ) обязательны для заполнения
  account.activation_required: Activation is required
  account.thanks_for_posting: Спасибо за оставленный вами запрос
  account.admin_check_and_approve: После проверки нашим Админом ваш лот будет размещен на нашем сайте!
  account.quantity_example: 3 литра
  account.currency: Валюта
  account.delivery_point_example: Mary
  account.upload_photo: Загрузить фото
  account.fee_for_publishing: За публикацию с вашего баланса будет снято :fee TMT
  account.publish: Опубликовать
  topnav.reg: Agza bol
  topnav.login: Giriş
  nav.home: Baş sahypa
  nav.city: Aşgabat
  page.more: Ýene
  page.not_found: Sahypa tapylmady.
  page.not_found_message: Bagyşlaň! Siziň gözleýän sahypaňyz ýyok.
  page.search: Gözleg
  page.search_result: 'Gözleg netijesi: :number makala tapyldy'
  page.new_prods: Täze harytlar
  page.prods: Harytlar
  page.prod_id: Lot
  page.prod_img: Surat
  page.prod_title: Haryt
  page.prod_amount: Sany
  page.prod_price: Başlangyç bahasy
  page.prod_finishdate: Gutarýan wagty
  page.prod_kg: kg
  page.pages: Sahypa
  page.contact_us: Обратная связь
  page.your_firstname: Ваше имя
  page.your_lastname: Ваша фамилия
  page.example: Пример
  page.example_firstname: Аман
  page.example_lastname: Аманов
  page.message: Сообщение
  page.describe_your_problem: Опишите вашу проблемму
  page.message_sent: Сообщение отправлено
  page.message_to_seller: Сообщение продавцу
  page.fio: ФИО
  footer.contacts: Kontaktlar
  footer.tel: Tel
  footer.email: El. bukja
  footer.address: Adres
  footer.copyright: © TDÇMB ähli hukuklar goralan
  footer.categories: Kategoriýalar
  status_approved: Tassyklandy
  status_draft: Garalama
  status_new: Barlagda
  status_denied: Tassyklanmady
  status_expired: Möhleti gutardy
  page.similar_prods: Из этой же категории
  page.prod_no: Номер лота
  page.prod_mark: Марка товара
  page.prod_vendor: Производитель
  page.prod_vendor_country: Страна производителя
  page.market_type: Market type
  page.market_type_option_in: Внутренний
  page.market_type_option_out: Внешний
  page.prod_desc: Описание
  page.prod_amount_2: Количество товара
  page.prod_price_2: Стартовая цена за единицу
  page.prod_startdate: Дата начала
  page.measure: Единица измерения
  page.payment_cond: Условия оплаты
  page.date_decrease: По убыванию
  page.date_increase: По возрастанию
  page.no_results_found: No results found
  page.sort_by_date: По дате
  page.delivery_cond: Условия поставки
  page.delivery_point: Пункт
  page.packaging: Упаковка
  page.packaging_yes: Bar
  page.packaging_no: Ýok
  page.seller_cont: Контакты продавца
  page.buy_now: Купить сейчас
  page.send_prod_request: Отправить запрос на лот

