en:
  site.name: 'Turkmenistan state birzha'
  site.short_name: 'ГТСБТ'
  auth.login: Login
  auth.password: Password
  auth.reg_continue: Продолжить регистрацию
  auth.account_recov: Если вы забыли свой логин или пароль, просим вас
                            восстановить его по <a href="#" class="form_link">ссылке.</a>
  auth.login_to_account: Войти в свой профиль
  auth.personal_data: Персональные данные
  auth.my_announces: Мои объявления
  auth.messages: Сообщения
  auth.logout: Выйти
  auth.add_announce: Добавить объявление
  topnav.reg: Sign up
  topnav.login: Sign in
  nav.home: 'Home'
  nav.city: 'Ashgabat'
  page.more: 'More'
  page.not_found: 'Page not found'
  page.not_found_message: "We're sorry, but the page you requested cannot be found."
  page.search: 'Search'
  page.search_result: 'The search results found: :number articles'
  page.new_prods: Новые товары
  page.prod_id: Лот
  page.prod_img: Изображение
  page.prod_title: Товар
  page.prod_amount: Количество
  page.prod_price: Стартовая цена
  page.prod_finishdate: Дата окончания
  page.prod_kg: 'кг'
  page.pages: 'Страниц'
  footer.contacts: Контакты
  footer.tel: Тел
  footer.email: Эл. почта
  footer.address: Адрес
  footer.copyright: '© TDHСMB all rights reserved'
  footer.categories: 'Categories'
ru:
  site.name: '«Туркменистан: золотой век»'
  site.short_name: 'ГТСБТ'
  auth.login: 'Ваш логин'
  auth.password: Пароль
  auth.reg_continue: Продолжить регистрацию
  auth.account_recov: Если вы забыли свой логин или пароль, просим вас
                            восстановить его по <a href="#" class="form_link">ссылке.</a>
  auth.login_to_account: Войти в свой профиль
  auth.personal_data: Персональные данные
  auth.my_announces: Мои объявления
  auth.messages: Сообщения
  auth.logout: Выйти
  auth.add_announce: Добавить объявление
  topnav.reg: Регистрация
  topnav.login: Sign in
  nav.home: 'Главная'
  nav.city: 'Ашхабад'
  page.more: 'Ещё'
  page.not_found: 'Страница не найдена'
  page.not_found_message: "Сожалеем, но запрошенная вами страница не может быть найдена."
  page.search: 'Поиск'
  page.search_result: 'По результату поиска было найдено: :number статьи'
  page.new_prods: Новые товары
  page.prod_id: Лот
  page.prod_img: Изображение
  page.prod_title: Товар
  page.prod_amount: Количество
  page.prod_price: Стартовая цена
  page.prod_finishdate: Дата окончания
  page.prod_kg: 'кг'
  page.pages: 'Страниц'
  footer.contacts: Контакты
  footer.tel: Тел
  footer.email: Эл. почта
  footer.address: Адрес
  footer.copyright: '© TDHСMB все права зашишены'
  footer.categories: 'Categories'
tm:
  site.name: 'Türkmenistanyň Döwlet çig-mal biržasy'
  site.short_name: 'ГТСБТ'
  auth.login: 'Ваш логин'
  auth.password: Пароль
  auth.reg_continue: Продолжить регистрацию
  auth.account_recov: Если вы забыли свой логин или пароль, просим вас
                            восстановить его по <a href="#" class="form_link">ссылке.</a>
  auth.login_to_account: Войти в свой профиль
  auth.personal_data: Персональные данные
  auth.my_announces: Мои объявления
  auth.messages: Сообщения
  auth.logout: Выйти
  auth.add_announce: Добавить объявление
  topnav.reg: Hasaba almak
  topnav.login: Sign in
  nav.home: 'Baş sahypa'
  nav.city: 'Aşgabat'
  page.more: 'Ýene'
  page.not_found: 'Sahypa tapylmady.'
  page.not_found_message: "Bagyşlaň! Siziň gözleýän sahypaňyz ýyok."
  page.search: 'Gözleg'
  page.search_result: 'Gözleg netijesi: :number makala tapyldy'
  page.new_prods: Новые товары
  page.prod_id: Лот
  page.prod_img: Изображение
  page.prod_title: Товар
  page.prod_amount: Количество
  page.prod_price: Стартовая цена
  page.prod_finishdate: Дата окончания
  page.prod_kg: 'кг'
  page.pages: 'Страниц'
  footer.contacts: Контакты
  footer.tel: Тел
  footer.email: Эл. почта
  footer.address: Адрес
  footer.copyright: '© TDHСMB ähli hukuklar goralan'
  footer.categories: 'Categories'
